### ISSUE TITLE
Firmware available different than logs

### ISSUE THREAD

**Issue by pdcmoreira** [marthoc/docker-deconz#319]
I wanted to do a quick firmware update, following these steps:
https://github.com/marthoc/docker-deconz#updating-conbeeraspbee-firmware

First of all, I've updated the container (using the stable tag).

Then, following those steps, the logs are reporting the update file `deCONZ_ConBeeII_0x26660700.bin.GCF`:
```
deconz           | 16:15:26:073 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26660700.bin.GCF
deconz           | 16:15:26:073 GW firmware version: 0x26580700
deconz           | 16:15:26:074 GW firmware version shall be updated to: 0x26660700
```

But the update script doesn't suggest the availability of that file:
```
Firmware available for flashing:

deCONZ_ConBeeII_0x264a0700.bin.GCF
deCONZ_ConBeeII_0x26580700.bin.GCF
deCONZ_Rpi_0x26330500.bin.GCF
deCONZ_Rpi_0x26350500.bin.GCF
```

My guess is that the logs report the latest version available at http://dresden-light.appspot.com/discover, but the container doesn't have that file included yet.

Is there a way to make it `wget` the file, or something? Or is it not recommended to update to a version other than the ones included? (In this is the case, I think the version suggested on the logs should be the latest included.)

**Comment by Jo-Be-Co** [comment]
Hi @pdcmoreira,
are you sure that you have used the same container and/or version?

In your first snippet there is a file called `deCONZ_ConBeeII_0x26660700.bin.GCF`. The `firmware-update.sh` is just listing the same folder - so the file has to be seen ...

Nevertheless: if you start the update with a current version, you can enter the file name even if it is not currently in the directory. In that case the script will ask you if it should try a download.

**Comment by pdcmoreira** [comment]
Hi @Jo-Be-Co , thanks for your reply.

> are you sure that you have used the same container and/or version?

This was the problem. I had to adjust the run command to use docker-compose, since that's what I'm using.
After a bit of reading, I came up with the following solution:

In order to do the same as `docker -it`, since the `-i` and `-t` options aren't available from the docker-compose command line, I had to add the following options to the docker-compose service:
```yaml
  deconz:
    # ...
    stdin_open: true
    tty: true
```

Then I ran the command like this:
```bash
docker-compose run --rm --no-deps --entrypoint "/firmware-update.sh" -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys deconz
```

**Comment by larsfjaera** [comment]
Hi @pdcmoreira,  

I am not sure if you have resolved your issue, but I wanted to chime in with a potential solution, as I had the exact same problem as you. I also use docker-compose, and tried to run the update command, but was left with only old firmware versions. I also noted that the GCFFlasher was the version 3_03 which is outdated.

However, I noted that in my docker-compose file I have used the deconz tag `amd64`. Thus, since you used the `stable` tag, have you tried specifying it in the run command as such?
`docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz:stable`

When I used the same command, only specifying `amd64` I was presented with the latest version of GCFFlasher (v03_17) as well as the latest firmware. And I had no trouble running the command, even though I am using docker-compose.

**Comment by Mimiix** [comment]
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)

**Comment by pdcmoreira** [comment]
@larsfjaera @Mimiix Yes, my issue was solved the way I described in my previous comment.

**Comment by Mimiix** [comment]
@pdcmoreira Good to hear that :)
