### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by kccarbone** [marthoc/docker-deconz#32]
Maybe I'm missing something, but I just can not seem to get this to work on macOS. I can see the usb dongle in my /dev directory in macOS but I can't get it to connect to the container. Debugging a little I found the error: `docker: Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/ttyUSB0": lstat /dev/ttyUSB0: no such file or directory.`

I can resolve this error by adding --privileged to the run params, but the container still doesn't seem to mount the device internally. If I connect to the container and `ls /dev`, the device just isn't there.

What am I missing? I followed the directions under "Docker for Mac" to the letter, using explicit ports instead of shared host networking. I can connect to the Phoscon web app just fine but since the usb device doesn't exist there isn't much I can do.

**Comment by fregol** [comment]
If the problem is that Conbee is not created as /dev/ttyUSB0 on Mac host, so the Docker daemon can’t find it, what will be then the solution?
Sorry I’m just in the way of learning..
Thanks for your help

**Comment by marthoc** [comment]
The solution is to pass the correct device into the container (ie sub /dev/ttyUSB0 for what your device is actually created as).

**Comment by fregol** [comment]
I appreciate your quick response. Unfortunately I'm not still able to run deCONZ on my Mac mini.
This is what I've done so far:
1. Installed Docker for Mac v. 2.0.0.3 (it is running)
2. Inserted CONBEE in a USB port (nothing else is connected)
3. Gave command:
docker run -d \
    --name=deconz \
    -p 80:80 \
    -p 443:443 \
    --restart=always \
    -v /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ \
    --device=/dev/ttyUSB0 \
    -e DECONZ_WEB_PORT=80 \
    -e DECONZ_WS_PORT=443 \
    marthoc/deconz

Then, the error pops up:
Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/cu.usbserial-DO01MNGG": no such file or directory.

as you can see, I tried to pass the correct device, searching into: ls /dev
but whatever I insert as device, the error is always the same.

Once again, thanks for your time and help

**Comment by mrystrand** [comment]
@fregol 

I received a Conbee (1) USB stick the other day and trying to get it to work on my Mac also, running Mojave latest stable and Docker with marthoc/docker-deconz.
My programming skills are not good though.

Have you been able to get it to work? If so, how?

With ls /dev I find my Conbee is named tty.usbserial-DM01BF0Y. I can install with --privileged otherwise I get errors;
docker: Error response from daemon: error gathering device information while adding custom device "/dev/tty.usbserial-DM01BF0Y": no such file or directory.

But with privileged I can access Phoscon (via my Macs IP adress) but the Conbee stick shows up as "Firmware: Not connected" and I cannot add any sensors or other devices..

Hoping to get some help here.

**Comment by MPV** [comment]
@mrystrand USB passthrough with Apple Hypervisor might be the culprit, see https://github.com/marthoc/docker-deconz/issues/146#issuecomment-541205794
