### ISSUE TITLE
USB device name changes after reboot

### ISSUE THREAD

**Issue by sljdhl** [marthoc/docker-deconz#338]
Hello. Sometimes when my computer restarts my container for deconz does not start due to the USB device has changed name. The USB is in the same port all the time. What is changing the name and can I prevent it some how? Restarting the container doesnt work either, a full computer reboot is needed for it to work, until it reboots again..

**Comment by manup** [comment]
It's baked into Linux and can unfortunately not be changed, the device can get a new name for various reasons.
And the new name isn't automatically visible in the container.

However there is a different way to start the container so this shouldn't be an issue, you might try the following:

https://github.com/marthoc/docker-deconz/issues/298#issuecomment-732293745

**Comment by martijndemulder** [comment]
I do feel this should be fixed in the docker build FI with the information provided in the post above.
I'm also using a Zwave stick and it's really annoying that every reboot (luckily there aren't many on a server) I have to check if the ACM0 is linked to the right device or not.
Every other docker i'm using is able to refer to the "path-by-id" directly and never give me issues.

A fix would be greatly appriciated!

**Comment by phdelodder** [comment]
This issue can be solved by using a "path-by-id" solution as mentioned in this issue. 

However this has nothing to do with the docker image itself.
