### ISSUE TITLE
Motion sensor silvercrest (lidl) support

### ISSUE THREAD

**Issue by snhnic** [marthoc/docker-deconz#346]
I understood sensor motion from silvercrest is supported in deconz 2.7 but the latest martic/deconz is showing version 2.6. 

On Synology 218 phoscon app installation

**Comment by franzda** [comment]
Hi there
I use Raspberry / openhab 2.5.1 / deCONZ.
I installed both version 2.07.02 and 2.09.01. The behavior is the same. The sensor is recognized and runs fine on / in openhab 2,5.1(the integration is quite shaky but it works)

An open point is the duration of the detection display. 

The sensor displays "detected" for 65 seconds. In the rule, it must be taken into account when and how the next detection is to be recognized because no second detection is registered while detection is being displayed. 

(but this is not an issue just needs to be considered)

Times shorter than 65 seconds (as far as I have seen) are not possible the is no way to change this value (as far as I have seen) 

We can exchange ideas about the rule definition in openhab

**Comment by scobby** [comment]
please post application specific problems here:

https://github.com/dresden-elektronik/deconz-rest-plugin

this repo is only for the docker implementation.

**Comment by snhnic** [comment]
> please post application specific problems here:
> 
> https://github.com/dresden-elektronik/deconz-rest-plugin
> 
> this repo is only for the docker implementation.

You make this far to difficult. I have a simple question but nobody seem to have the right answer. How can I get the correct version in Docker. Now it is 2.06.00 / 11/15/2020 - 26660700 and I believe it is a Docker question since it is installed with an image.

**Comment by phdelodder** [comment]
Using the Synology interface...

Go to Registry, locate the image you want to update; click download and choose tag "latest". The download will replace the former image.

When the image download is complete, stop the container, click "clear" and then "start". Done.

The container may "disappear" momentarily when "clear" is clicked. Do not panic.
