### ISSUE TITLE
Include socat to the addon to use ser2net

### ISSUE THREAD

**Issue by martikainen87** [marthoc/docker-deconz#66]
Hi

I'm looking for a good way to make a portable gateway for zigbee/z-wave/other usb stick using raspberry Pi with a powerbank and utilize ser2net and socat.

Would you mind taking a look if you can add socat to your addon? Would be real nice to have a pi running with minimal software and just pass through the usb over ip to another server and run decons on that server. Also a good way if you have a cluster and want to move your HA server to another node when patching, or if you have a test installation of HA for trying out new code.

The installation is not that big and pretty straight forward, I was thinking of making my own addon but would rather see it in your "official" addon so that more may gain from it. 
And I'm guessing more than me would like an easy way to just move the conbee stick to the zigbee device you want to include and just add it, instead of moving the zigbee device to the server which can be troublesome for light bulbs and other stuff which isn't as portable as a xiaomi motion sensor. 

Here's a link to a guide on how it works.

https://community.openhab.org/t/share-z-wave-dongle-over-ip-usb-over-ip-using-ser2net-socat-guide/34895

**Comment by Kane610** [comment]
With deconz it is easier to just run on a different machine than what you're suggesting

**Comment by martikainen87** [comment]
Yeah I know that it works like that, but I would rather have the deconz software on my main server with constant backups running, and not be worried about the SD-card getting corrupt, had my fair share of data loss already =/

**Comment by marthoc** [comment]
I understand the motivation but I'm having a hard time thinking of how it would work in practice - I guess environment variables would need to be defined for remote ip... but do you even know how deCONZ would handle network drops/disconnections from the hardware? I'm guessing since it isn't intended to run that way it wouldn't be very graceful...

**Comment by martikainen87** [comment]
Haven't thought about the events of network issues, small or big. I guess that's something that needs testing to see if it's very sensitive for drops or if it can handle a few packages being lost, or even a few seconds without connection. 

I would gladly help you test it, I'm well experienced with HA, docker etc, but totaly bad at programming, which is why I would rather see if you would think it could be doable :)

**Comment by marthoc** [comment]
One way to test how deCONZ handles the disconnection is to unplug your USB stick while deCONZ is running, then plug it back in - because to deCONZ that's the same thing that would happen if the network were to drop when using socat/ser2net. What happens? Another consideration is, does socat try to reconnect and reestablish communication after a dropped connection?

**Comment by martikainen87** [comment]
I'm running a pretty "special" setup as I have ESXi -> Ubuntu VM -> Docker -> Hassio -> Deconz(addon) 

And If i do these tests now my USB stick will go from ttyUSB0 to ttyUSB1 on my ubuntuVM host. And I'm guessing that wont be the same of we have told socat that it should use IP:PORT and mount to dev/Whatever. 

But I could setup a Pi and test this outside of HA, just to see how socat handles the disconnects and remounting.
